apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-ad-insertion
  namespace: mediagenai-aws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-ad-insertion
  template:
    metadata:
      labels:
        app: dynamic-ad-insertion
    spec:
      containers:
        - name: dynamic-ad-insertion
          image: 462634386586.dkr.ecr.us-east-1.amazonaws.com/mediagenai/dynamic-ad-insertion:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5010
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: MEDIA_S3_BUCKET
              value: mediagenai-462634386586
            - name: DAI_S3_BUCKET
              value: mediagenai-462634386586
---
apiVersion: v1
kind: Service
metadata:
  name: dynamic-ad-insertion
  namespace: mediagenai-aws
spec:
  type: ClusterIP
  selector:
    app: dynamic-ad-insertion
  ports:
    - name: http
      port: 5010
      targetPort: 5010
